<?php

namespace Proxies\__CG__\IHQS\NuitBlancheBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class User extends \IHQS\NuitBlancheBundle\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function serialize()
    {
        $this->__load();
        return parent::serialize();
    }

    public function unserialize($data)
    {
        $this->__load();
        return parent::unserialize($data);
    }

    public function prePersist()
    {
        $this->__load();
        return parent::prePersist();
    }

    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getUsername()
    {
        $this->__load();
        return parent::getUsername();
    }

    public function setUsername($username)
    {
        $this->__load();
        return parent::setUsername($username);
    }

    public function getPassword()
    {
        $this->__load();
        return parent::getPassword();
    }

    public function setPassword($password)
    {
        $this->__load();
        return parent::setPassword($password);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getAvatar()
    {
        $this->__load();
        return parent::getAvatar();
    }

    public function getAvatarUrl()
    {
        $this->__load();
        return parent::getAvatarUrl();
    }

    public function getAvatarMargin()
    {
        $this->__load();
        return parent::getAvatarMargin();
    }

    public function setAvatar($avatar)
    {
        $this->__load();
        return parent::setAvatar($avatar);
    }

    public function getFirstName()
    {
        $this->__load();
        return parent::getFirstName();
    }

    public function setFirstName($firstName)
    {
        $this->__load();
        return parent::setFirstName($firstName);
    }

    public function getLastName()
    {
        $this->__load();
        return parent::getLastName();
    }

    public function setLastName($lastName)
    {
        $this->__load();
        return parent::setLastName($lastName);
    }

    public function getCity()
    {
        $this->__load();
        return parent::getCity();
    }

    public function setCity($city)
    {
        $this->__load();
        return parent::setCity($city);
    }

    public function getCountry()
    {
        $this->__load();
        return parent::getCountry();
    }

    public function getCountryCode()
    {
        $this->__load();
        return parent::getCountryCode();
    }

    public function setCountry($country)
    {
        $this->__load();
        return parent::setCountry($country);
    }

    public function getFacebook()
    {
        $this->__load();
        return parent::getFacebook();
    }

    public function setFacebook($facebook)
    {
        $this->__load();
        return parent::setFacebook($facebook);
    }

    public function getTwitter()
    {
        $this->__load();
        return parent::getTwitter();
    }

    public function setTwitter($twitter)
    {
        $this->__load();
        return parent::setTwitter($twitter);
    }

    public function getSkype()
    {
        $this->__load();
        return parent::getSkype();
    }

    public function setSkype($skype)
    {
        $this->__load();
        return parent::setSkype($skype);
    }

    public function getMsn()
    {
        $this->__load();
        return parent::getMsn();
    }

    public function setMsn($msn)
    {
        $this->__load();
        return parent::setMsn($msn);
    }

    public function getLastActivity()
    {
        $this->__load();
        return parent::getLastActivity();
    }

    public function setLastActivity(\DateTime $lastActivity)
    {
        $this->__load();
        return parent::setLastActivity($lastActivity);
    }

    public function lastSeen()
    {
        $this->__load();
        return parent::lastSeen();
    }

    public function getStatus()
    {
        $this->__load();
        return parent::getStatus();
    }

    public function getPublicMsn()
    {
        $this->__load();
        return parent::getPublicMsn();
    }

    public function getSc2()
    {
        $this->__load();
        return parent::getSc2();
    }

    public function setSc2(\IHQS\NuitBlancheBundle\Entity\SC2Profile $sc2)
    {
        $this->__load();
        return parent::setSc2($sc2);
    }

    public function getWow()
    {
        $this->__load();
        return parent::getWow();
    }

    public function setWow(\IHQS\NuitBlancheBundle\Entity\WoWProfile $wow)
    {
        $this->__load();
        return parent::setWow($wow);
    }

    public function getProfiles()
    {
        $this->__load();
        return parent::getProfiles();
    }

    public function addRole($role)
    {
        $this->__load();
        return parent::addRole($role);
    }

    public function getRoles()
    {
        $this->__load();
        return parent::getRoles();
    }

    public function getSalt()
    {
        $this->__load();
        return parent::getSalt();
    }

    public function eraseCredentials()
    {
        $this->__load();
        return parent::eraseCredentials();
    }

    public function equals(\Symfony\Component\Security\Core\User\UserInterface $user)
    {
        $this->__load();
        return parent::equals($user);
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'username', 'password', 'email', 'avatar', 'firstName', 'lastName', 'city', 'country', 'facebook', 'twitter', 'skype', 'msn', 'roles', 'lastActivity', 'news', 'uploadedReplays', 'sc2', 'wow');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}