<?php

namespace IHQS\NuitBlancheBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ReplayController__JMSInjector
{
    public static function inject($container) {
        $instance = new \IHQS\NuitBlancheBundle\Controller\ReplayController();
        return $instance;
    }
}
