<?php

namespace IHQS\NuitBlancheBundle\Model;

use Doctrine\ORM\EntityRepository;
use IHQS\NuitBlancheBundle\Entity\Game;
use IHQS\NuitBlancheBundle\Entity\Replay;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->createQueryBuilder('g')
            ->orderBy('g.id', 'DESC')
            ->getQuery()
            ->execute()
        ;
    }

    public function findAllWithReplay()
    {
        $games = $this->findAll();

        $result = array();
        foreach($games as $game)
        {
            if($game->getReplay() instanceof Replay)
            {
                array_push($result, $game);
            }
        }

        return $result;
    }

    public function findAllWithoutReplay()
    {
        return $this->createQueryBuilder('g')
            ->leftJoin('g.replay', 'r')
            ->where('r.game IS NULL')
            ->orderBy('g.id', 'DESC')
        ;
    }
}