<?php

namespace IHQS\NuitBlancheBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * NewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsRepository extends EntityRepository
{
    public function findLast()
    {
        list($news) = $this->createQueryBuilder('n')->
            orderBy('n.date', 'DESC')->
            setMaxResults(1)->
            getQuery()->
            execute();

        return $news;
    }

    public function findall()
    {
        $qb = $this->createQueryBuilder('n');

        return $qb->
            orderBy('n.date', 'DESC')->
            getQuery()->
            execute();
    }

    public function findLatest($community = false)
    {
        $qb = $this->createQueryBuilder('n');

        $where_community = $community ? 'IS NULL' : 'IS NOT NULL';

        return $qb->
            where('n.team ' . $where_community)->
            orderBy('n.date', 'DESC')->
            setMaxResults(5)->
            getQuery()->
            execute();
    }
}