<?php

namespace IHQS\NuitBlancheBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends EntityRepository
{
    public function findConnected()
    {
        $limit = date('Y-m-d H:i:s', mktime(date('H'), date('i')-10, date('s'), date('m'), date('d'), date('Y'))) ;

        $qb = $this->createQueryBuilder('p');

        return $qb
            ->leftJoin('p.user', 'u')
            ->where(
                $qb->expr()->gte('u.lastActivity', $qb->expr()->literal($limit))
            )
            ->orderBy('u.lastActivity', 'DESC')
            ->getQuery()->execute();
    }
}