<?php

namespace IHQS\NuitBlancheBundle\Model;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\EntityManager;
use IHQS\NuitBlancheBundle\Entity\Replay;
use IHQS\NuitBlancheBundle\Processor\ReplayProcessor;
/**
 * ReplayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReplayRepository extends EntityRepository
{
	protected $replayProcessor;

	public function setReplayProcessor(ReplayProcessor $replayProcessor)
	{
		$this->replayProcessor = $replayProcessor;
	}
	
	public function createOne()
	{
		$replay = new Replay();
        $replay->setReplayProcessor($this->replayProcessor);
		return $replay;
	}

    public function findAll()
    {
        return $this->createQueryBuilder('r')->
            orderBy('r.id', 'DESC')->
            getQuery()->
            execute();
    }

    public function findLatest()
    {
        return $this->createQueryBuilder('r')->
            orderBy('r.id', 'DESC')->
            setMaxResults(5)->
            getQuery()->
            execute();
    }
}