<?php

namespace IHQS\NuitBlancheBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * SC2ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SC2ProfileRepository extends EntityRepository
{
}