<?php

namespace IHQS\NuitBlancheBundle\Model;

use Doctrine\ORM\EntityRepository;
use IHQS\NuitBlancheBundle\Entity\War;

/**
 * WarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WarRepository extends EntityRepository
{
	public function createOne()
	{
		
	}

    public function findAll()
    {
        return $this->createQueryBuilder('n')->
            orderBy('n.date', 'DESC')->
            getQuery()->
            execute();
    }

    public function findNextWars()
    {
        $qb = $this->createQueryBuilder('w');

        return $qb->
            where(
               $qb->expr()->gte('w.date', $qb->expr()->literal(date('Y-m-d H:i:s')))
            )->
            orderBy('w.date', 'ASC')->
            setMaxResults(4)->
            getQuery()->
            execute();
    }

    public function findLatest()
    {
        $qb = $this->createQueryBuilder('w');

        return $qb->
            where(
               $qb->expr()->lte('w.date', $qb->expr()->literal(date('Y-m-d H:i:s')))
            )->
            orderBy('w.date', 'DESC')->
            setMaxResults(5)->
            getQuery()->
            execute();
    }

    public function findByMonth($month)
    {
        $month_first_day = date('Y-') . $month . "-1" . " 00:00:01";
        $month_last_day  = date('Y-') . $month . date('-t') . " 23:59:59";

        $qb = $this->createQueryBuilder('w');

        return $qb->
            where($qb->expr()->andx(
                $qb->expr()->gte('w.date', $qb->expr()->literal($month_first_day)),
                $qb->expr()->lte('w.date', $qb->expr()->literal($month_last_day))
            ))->
            orderBy('w.date', 'DESC')->
            getQuery()->execute();
    }
}